name: Reusable UI Tests and Analysis

on:
  workflow_call:

permissions: {}

jobs:
  tests-frontend:
    name: Frontend UI Tests
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
    permissions:
      contents: write
      checks: write
    runs-on: ubuntu-24.04
    env:
      VITE_APP_NAME: Waste Plus
      VITE_FEATURES_OFFLINE: true
      VITE_ZONE: TEST
      VITE_USER_POOLS_ID: ${{ secrets.COGNITO_USER_POOL }}
      VITE_USER_POOLS_WEB_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
      VITE_LEGACY_BASE_URL: https://apps.nrs.gov.bc.ca/ext/waste-for
      VITE_CLIENT_BASE_URL: https://forestclient.nrs.gov.bc.ca
      VITE_BACKEND_URL: http://localhost:8080
      VITE_NODE_ENV: test
      VITE_COVERAGE: true
      VITE_PORT: 3000
    steps:
      - uses: actions/checkout@v5

      - name: Fix safe.directory for GitHub Actions
        run: git config --global --add safe.directory /__w/nr-app-name/nr-app-name

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm i
        working-directory: frontend

      - name: Frontend Tests
        run: npm run test:a11y
        working-directory: frontend

      - name: Annotate PR with a11y results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Accessibility Tests
          path: frontend/test-reports/junit/report.xml
          reporter: java-junit
          only-summary: false
          fail-on-error: true

      - name: Upload test videos
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: a11y-videos
          path: frontend/test-results/videos/

      - name: Upload test results
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: a11y-reports
          path: frontend/test-reports/report/
